services:
  # Frontend (Angular App)
  - type: web
    name: quiz-frontend
    env: static
    rootDir: .
    buildCommand: "npm install && npm run build --configuration production"
    staticPublishPath: "dist/aptitude-game-site"
    envVars:
      - key: NODE_VERSION
        value: 18

  # Backend (Node.js Socket Server)
  - type: web
    name: quiz-backend
    env: node
    rootDir: socket-server
    buildCommand: "npm install"
    startCommand: "node server.js"   # change to "npm start" if your package.json has start script
    envVars:
      - key: NODE_VERSION
        value: 18
      # Firebase credentials here
      - key: FIREBASE_API_KEY
        value: your_api_key
      - key: FIREBASE_PROJECT_ID
        value: your_project_id
